### ISSUE TITLE
Where the _Idx files come from?

### ISSUE THREAD

**Issue by agcala** [arapat/jboost#1]
When trying to perform a multi-label classification, I stumble upon the following error 

`FileNotFoundError: [Errno 2] No such file or directory: 'data_labels_idx.`

I can see all the examples have that file included, yet this _idx files are not mentioned anywhere in the docs.  Can anybody give me a clue on how this file comes about?

**Comment by arapat** [comment]
Is it generated by this script?

https://github.com/arapat/jboost/blob/master/scripts/AddRandomIndex.README

**Comment by agcala** [comment]
**Certainly is.** Thank you. 

- The docs never said anything about that. 
- The [**FAQ**](http://jboost.wiki.sourceforge.net/FAQ) section link is broken. 
- The Python interface is written in Python 2.7 when [the current Python version is 3.8.0](https://www.python.org/downloads/release/python-380/)

Other than that everything seems to work fine. Great project. Thank you.

**Comment by arapat** [comment]
Unfortunately this project is no longer being maintained. I recommend trying out other boosting implementations, such as [xgboost](https://github.com/dmlc/xgboost) and [LightGBM](https://github.com/microsoft/LightGBM).
